initial items set-up
JustasBan/kinder-app pull request #1
Opened 2021-11-30 22:06 UTC by JustasBan

with db, class and misc. types

2021-11-30 22:09 UTC, The-Blue-K commented
Something strange with github, where after pulling project, most of the projects files say they need to be committed. Most of these changes are auto-generated.

2021-11-30 22:24 UTC, JustasBan commented
git ignore prob not set up correctly

2021-11-30 22:25 UTC, The-Blue-K requested changes
Authorization needs to be added to the creation, editing and deletion of items.
Please correct the repeating misspelling of category as cathegory.

2021-11-30 22:25 UTC, The-Blue-K commented on kinder-app/Data/Migrations/ApplicationDbContextModelSnapshot.cs
> +                    b.Property<int>("Cathegory")
Category*

2021-11-30 22:25 UTC, The-Blue-K commented on kinder-app/Models/CathegoryEnum.cs
> +    public enum CathegoryEnum
Category*

2021-11-30 22:25 UTC, The-Blue-K commented on kinder-app/Models/ConditionEnum.cs
> +        Fair
Might wanna add conditions for poor, very poor and broken.

2021-11-30 22:25 UTC, The-Blue-K commented on kinder-app/Models/Item.cs
> +        public CathegoryEnum Cathegory { get; set; }
Category*

2021-11-30 22:25 UTC, The-Blue-K commented on kinder-app/Controllers/ItemsController.cs
> +        }
Why are there no Authorize annotations? now anyone can create, edit and delete items without being logged in.

2021-11-30 22:25 UTC, The-Blue-K commented on kinder-app/Data/Migrations/20211130215847_InitialItems.cs
> +                    Cathegory = table.Column<int>(type: "int", nullable: false),
Should be changed to category in the model so the mistake is not reflected in db.

2021-11-30 22:25 UTC, The-Blue-K commented on kinder-app/Models/Item.cs
> +            str += Cathegory.ToString() + ';';
Category*

2021-11-30 22:43 UTC, JustasBan commented on kinder-app/Models/ConditionEnum.cs
> +        Fair
poor and very poor fall behind fair category but broken is a nice addition

2021-11-30 22:44 UTC, JustasBan commented on kinder-app/Controllers/ItemsController.cs
> +        }
i will add that to other PR, right now just initialise

2021-12-01 00:15 UTC, JustasBan commented
future improvements needed

2021-12-01 00:15 UTC, merged